# Generated by Django 4.2 on 2024-07-19 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_gstrates_billing_cgst_billing_igst_billing_sgst_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='cgst',
            new_name='cgst_amount',
        ),
        migrations.RenameField(
            model_name='billing',
            old_name='igst',
            new_name='cgst_rates',
        ),
        migrations.RenameField(
            model_name='billing',
            old_name='sgst',
            new_name='igst_amount',
        ),
        migrations.AddField(
            model_name='billing',
            name='igst_rates',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billing',
            name='is_inter_state',
            field=models.BooleanField(default=False, help_text='Is this an inter-state transaction?'),
        ),
        migrations.AddField(
            model_name='billing',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billing',
            name='sgst_rates',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 21, 35, 2, 503669)),
        ),
        migrations.AlterField(
            model_name='billing',
            name='billing_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 21, 35, 2, 502151)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 21, 35, 2, 499826)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 21, 35, 2, 499314)),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 21, 35, 2, 503236)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 21, 35, 2, 501315)),
        ),
        migrations.AlterField(
            model_name='organization',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 21, 35, 2, 497679)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 21, 35, 2, 496922)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='will_expire_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 21, 35, 2, 496945)),
        ),
        migrations.AlterField(
            model_name='product',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 21, 35, 2, 500799)),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 21, 35, 2, 500252)),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 21, 35, 2, 498090)),
        ),
        migrations.AlterField(
            model_name='twofactorverification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 21, 35, 2, 497340)),
        ),
    ]
